create table cities
(
    id         serial primary key,
    name       text,
    population int
);

-- getting autogenerated id (in SQL)
INSERT INTO cities(name, population)
VALUES ('Ufa', 1000000)
RETURNING (id);